title: Cosmic Carnage Project
description: "TEAM EATER PROJECT!"
owner_name: Cosmic-Carnage 
Codershub_username: Cosmic-Carnage
baseurl: "/cosmic"
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
